apiVersion: v1
kind: Service
metadata:
  name: demo2-api
  namespace: demo
spec:
  selector:
    app: demo2-api
  type: LoadBalancer
  ports:
    - protocol: TCP
      name: demo2-api
      port: 80
      targetPort: 80