apiVersion: v1
kind: Service
metadata:
  name: demo2-web
  namespace: demo
spec:
  selector:
    app: demo2-web
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080