apiVersion: v1
kind: Service
metadata:
  name: demo1-api
  namespace: demo
spec:
  selector:
    app: demo1-api
  type: LoadBalancer
  ports:
    - protocol: TCP
      name: demo1-api
      port: 80
      targetPort: 80